name: tinker_manager
description: This is thinker patch mamanger platform

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  json_serializable: ^6.6.2
  file_selector: ^0.9.3
  dio: ^5.1.2
  url_launcher: ^6.1.11
  easy_refresh: ^3.3.2+1
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  json_serializable: ^6.6.2
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - images/
